[build-system]
  requires = ['setuptools>=61.0.0']
  build-backend = 'setuptools.build_meta'

[tool.setuptools]
  packages = ["pytomofilt"]

[project]
  name = "climate-aware-task-scheduler"
  dynamic = ["version"]
  description = "Climate aware task scheduler"
  authors = [
    { name = "Justin Leung" },
    { name = "Andrew Walker"},
  ]
  license = { file = "LICENSE" }
  requires-python = ">=3.9"
  readme = "README.md"
  classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
  ]
  dependencies = ["pyshtools", "cartopy", "terratools", "pytest", "numba", "scipy", "numpy"]

  [tool.setuptools.dynamic]
    version = 0.1

